<img height="80px" src="<?= $block->getImageUrl() ?>" alt="ApiCheck Logo" />

<p>
    Met onze adres Validatie API weet je 100% zeker dat je klanten het juiste adres en e-mailadres invullen.<br>
    Op basis van het geselecteerde land maken wij het de klant zo makkelijk mogelijk om een adres in te voeren.<br>
    Voor Nederland is een postcode, huisnummer en eventueel toevoeging al voldoende voor een volledig en compleet adres.
</p>